/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChuongChapterRouteImport } from './routes/chuong/$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ChuongChapterRoute = ChuongChapterRouteImport.update({
  id: '/chuong/$chapter',
  path: '/chuong/$chapter',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chuong/$chapter.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chuong/$chapter': typeof ChuongChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chuong/$chapter': typeof ChuongChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chuong/$chapter': typeof ChuongChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chuong/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chuong/$chapter'
  id: '__root__' | '/' | '/chuong/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChuongChapterRoute: typeof ChuongChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chuong/$chapter': {
      id: '/chuong/$chapter'
      path: '/chuong/$chapter'
      fullPath: '/chuong/$chapter'
      preLoaderRoute: typeof ChuongChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChuongChapterRoute: ChuongChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
